services:
  postgres:
    image: postgres:15
    container_name: agent-runtime-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-durable}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-durable}
      POSTGRES_DB: ${POSTGRES_DB:-durable}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-durable} -d ${POSTGRES_DB:-durable}"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    image: ghcr.io/adiadia/agent-runtime-api:${IMAGE_TAG:-latest}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      HTTP_ADDR: ${HTTP_ADDR:-:8080}
      DATABASE_URL: ${DATABASE_URL:-postgres://durable:durable@postgres:5432/durable?sslmode=disable}
      ENV: ${ENV:-dev}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      ADMIN_TOKEN: ${ADMIN_TOKEN:-change-me-admin-token}
      AUTO_MIGRATE: ${AUTO_MIGRATE:-true}
    ports:
      - "${API_PORT:-8080}:8080"
    restart: unless-stopped

  worker:
    profiles: ["worker"]
    image: ghcr.io/adiadia/agent-runtime-worker:${IMAGE_TAG:-latest}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://durable:durable@postgres:5432/durable?sslmode=disable}
      ENV: ${ENV:-dev}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      AUTO_MIGRATE: ${AUTO_MIGRATE:-true}
    command:
      - "--api-key-id=${WORKER_API_KEY_ID:-}"
      - "--poll-interval=${WORKER_POLL_INTERVAL:-250ms}"
      - "--max-attempts=${WORKER_MAX_ATTEMPTS:-3}"
      - "--reclaim-after=${WORKER_RECLAIM_AFTER:-5m}"
      - "--retry-base-delay=${WORKER_RETRY_BASE_DELAY:-2s}"
      - "--default-step-timeout=${WORKER_DEFAULT_STEP_TIMEOUT:-30s}"
    restart: unless-stopped

volumes:
  postgres-data:
