ALTER TABLE runs
    ADD COLUMN IF NOT EXISTS webhook_url TEXT NULL;

ALTER TABLE runs
    ADD COLUMN IF NOT EXISTS webhook_secret TEXT NULL;

ALTER TABLE runs
    ADD COLUMN IF NOT EXISTS total_cost_usd NUMERIC(10,6) NOT NULL DEFAULT 0;

ALTER TABLE steps
    ADD COLUMN IF NOT EXISTS cost_usd NUMERIC(10,6) NOT NULL DEFAULT 0;
